# Generated by Django 5.0.1 on 2024-02-05 06:01
''' migration modules import '''
from django.db import migrations, models


class Migration(migrations.Migration):
    ''' migration class defined'''
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id',
                 models.BigAutoField(auto_created=True,
                 primary_key=True,
                 serialize=False,
                 verbose_name='ID'
                 )),
                ('username', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=30)),
                ('password', models.CharField(max_length=30)),
            ],
        ),
    ]
