# Generated by Django 5.0.1 on 2024-02-22 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0002_register_delete_person'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Register',
        ),
    ]
